#!/bin/sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in pacman mount umount su poweroff reboot ; do
  alias $command="sudo $command"
done; unset command

# Make aliases work with sudo
alias sudo="sudo "

# Sane defaults
alias \
  cp="cp -iv" \
  ffmpeg="ffmpeg -hide_banner" \
  mkdir="mkdir -pv" \
  mv="mv -iv" \
  rsync="rsync -vrPlu"

# Color
alias \
  cat='bat' \
  diff="diff --color=auto" \
  ip='ip -color=auto' \
  ls="exa -a --color=auto --group-directories-first"

# git
alias \
  glog="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"

# Copy & Paste
alias \
  pbcopy="xsel --input --clipboard" \
  pbpaste="xsel --output --clipboard"

# Misc
alias \
  fetch="fastfetch" \
  ka="killall" \
  lf="lfub" \
  mirrors="sudo reflector -c IN --sort rate -a 24 -f 5 -p https --save /etc/pacman.d/mirrorlist" \
  newsboat="newsboat -u $HOME/doc/urls" \
  obs="DRI_PRIME=0 obs" \
  purge="pacman -Qtdq | pacman -Rsunc -" \
  rm='echo "Use trash <file> instead."; false' \
  trash="gio trash" \
  wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"

