#!/bin/sh

# use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in pacman mount umount su poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

alias \
	ls="ls -ahN --color=auto --group-directories-first" \
  ip='ip -color=auto' \
  cat='bat --theme="Visual Studio Dark+"' \
	grep="rg --color=auto" \
	diff="diff --color=auto"

alias \
	sudo='sudo ' \
	cp="cp -iv" \
	mv="mv -iv" \
	rm='echo "This is not the command you are looking for."; false' \
	mkdir="mkdir -pv" \
	wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts" \
  lf="lfub" \
  ka="killall" \
	config="/usr/bin/git --git-dir=$HOME/.dots/ --work-tree=$HOME" \
	purge="pacman -Qtdq | pacman -Rns -"

alias \
  zathura="devour zathura" \
  newsboat="newsboat -u /mnt/games/urls" \
  mpv="devour mpv" \
  libreoffice="devour libreoffice"

alias \
  g="git " \
  gst="git status" \
  gaa="git add " \
  gcm="git commit -m " \
  gpu="git push origin " \
  gcb="git checkout -b " \
  gsw="git switch " \
  gpl="git pull origin " \
  glog="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"

