#!/bin/sh

# use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount su poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

alias \
	sudo='sudo ' \
	cp="cp -iv" \
	mv="mv -iv" \
	rm='echo "This is not the command you are looking for."; false' \
	bc="bc -ql" \
	mkdir="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts" \
	ls="ls -ahN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
  ka="killall" \
	trem="transmission-remote" \
  d="devour " \
  newsboat="newsboat && cat ~/.cache/wal/sequences" \
	config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
	purge="pacman -Qtdq | pacman -Rns -" \
  upgrade="yay; flatpak update"

alias \
  g="git " \
  gst="git status" \
  gaa="git add " \
  gcm="git commit -m " \
  gpu="git push origin " \
  gcb="git checkout -b " \
  gsw="git switch " \
  gpl="git pull origin " \
  glog="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'" 


