#!/bin/sh

# use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	sudo='sudo ' \
	cp="cp -iv" \
	mv="mv -iv" \
	rm='echo "This is not the command you are looking for."; false' \
	bc="bc -ql" \
	mkdir="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"  

# Colorize commands when possible.
alias \
	ls="ls -ahN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" 

# These common commands are just too long! Abbreviate them.
alias \
  ka="killall" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now"  \
  d="devour " \
  ranger="ranger && (cat ~/.cache/wal/sequences &) "

alias \
	config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
	purge="pacman -Qtdq | pacman -Rns -" \
  upgrade="yay;flatpak update"
  
