[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000
restore_state = true

[logging]
verbosity = 0
format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
color = true
config_file = 

[audio]
mixer = software
mixer_volume = 
output = autoaudiosink
buffer_time = 

[file]
enabled = false

[http]
enabled = false

[m3u]
enabled = false

[softwaremixer]
enabled = true

[stream]
enabled = false

[ytmusic]
enabled = true
auth_json=/home/ghoul/.config/mopidy/auth.json
auto_playlist_refresh = 60
youtube_player_refresh = 15
playlist_item_limit = 100
subscribed_artist_limit = 100
enable_history = true
enable_liked_songs = true
enable_mood_genre = true
enable_scrobbling = true
stream_preference = 
  141
  251
  140
  250
  249
verify_track_url = true

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
