# Change the prefix key to tilda
set -g prefix `

# Statusbar-tweaking
date="#[fg=#00000F,bg=#698DDA,nobold,nounderscore,noitalics] 󰃭  #[fg=#6e8fda,bg=#3b4261] %H:%M:%S "
status_left="#[bg=default,fg=default,bold]#{?client_prefix, [ . ] , #{session_name}}"
status_right="#S"
window_status_format=' #I:#W '

set -g status-position bottom
set -g status-style bg=default
set -g status-justify centre
set -g status-right-length 20
set -g status-left-length 20
set -g status-interval 1

set-option -g window-status-format "${window_status_format}"
set-option -g window-status-current-format "#[bg=#698DDA,fg=#000000] ${window_status_format} "
set -g status-left "${status_left}"
set -g status-right "${date}"

# Set title for actual terminal-emulator
set -g set-titles off
set -g set-titles-string "#W"

set -g default-terminal "tmux-256color"

# Scrollback history limit
set -g history-limit 5000

# Set bell/ring enabled
# set-window-option -g visual-bell off
# set-window-option -g bell-action none
# set -g visual-activity off

# Don't keep windows around after they exit
set -g remain-on-exit off

# Count windows from 1
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber windows when some closes
set -g renumber-windows on

# Vi keys
set -g mode-keys vi
set -g status-keys vi
set -g escape-time 0
set -g repeat-time 40
set -gw automatic-rename on

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -T copy-mode-vi MouseDrag1Pane
bind p paste-buffer
bind C-p choose-buffer

# Keybinds
bind b previous-window
bind | split -hc "#{pane_current_path}"
bind '\' split -c "#{pane_current_path}"
bind q kill-pane
bind Q kill-window
bind ` send-key `
# Select Panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Creating Windows, Sessions
bind s switch-client -T newGroup
bind -T newGroup 'C' new-window -c "#{pane_current_path}"
bind -T newGroup 's' new-session

# Renaming
bind r switch-client -T renameGroup
bind -T renameGroup 'w' command-prompt "rename-window '%%'"
bind -T renameGroup 's' command-prompt "rename-session '%%'"

# Re-source tmux.conf
bind-key c source-file ~/.config/tmux/tmux.conf \; display-message 'Re-loaded tmux.conf'

# Change current tab (window) using alt+1-9 
bind -n M-1 selectw -t:1
bind -n M-2 selectw -t:2
bind -n M-3 selectw -t:3
bind -n M-4 selectw -t:4
bind -n M-5 selectw -t:5
bind -n M-6 selectw -t:6
bind -n M-7 selectw -t:7
bind -n M-8 selectw -t:8
bind -n M-9 selectw -t:9
# Enter copy-mode and scroll back
bind -n S-Pageup copy-mode -u
# Hide/show status-bar
bind z set-option status
# Overview-mode
bind t choose-tree -Zs
# Change focus
bind w selectp -t :.+
# Search
bind -n C-M-f copy-mode \; send-key ^S
# Pop-up window
bind p display-popup
# Move panes
#bind S-right swap-pane -D
#bind S-left swap-pane -U

# Break pane
bind-key B break-pane -d
# Zoom pane
bind-key m resize-pane -Z
# Scroll speed
bind -T copy-mode WheelUpPane select-pane \; send-keys -X -N 2 scroll-up
bind -T copy-mode WheelDownPane select-pane \; send-keys -X -N 2 scroll-down
# Keys to toggle monitoring activity in a window and the synchronize-panes option
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @resurrect-capture-pane-contents 'on'

if 'test ! -d ~/.config/tmux/plugins/tpm' \
  'run "git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm"'

run -b '~/.config/tmux/plugins/tpm/tpm'
