#!/bin/sh

xinput --set-prop "pointer:Razer Razer Viper Mini" 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop "pointer:SynPS/2 Synaptics TouchPad" 369 0
xset -dpms

# Autostart
gwe --hide-window &
set-wallpaper.sh
unclutter &
udiskie &
picom -b
sxhkd &
dwmblocks &

# WM/DE Bootup
session=dwm
case $session in
    dwm               ) ssh-agent dwm;;
    awesome           ) ssh-agent awesome;;
    *                 ) ssh-agent $1;;
esac
