xrandr --output HDMI-0 --mode 1440x900 --primary --output LVDS-1-1 --mode 1366x768 --right-of HDMI-0 --output VGA-0 --off
xbindkeys -f ~/.config/xbindkeys/config &
org.flameshot.Flameshot &
xinput --set-prop "  CB Gaming" 'libinput Accel Profile Enabled' 0, 1 
xinput --set-prop "SynPS/2 Synaptics TouchPad" 369 0 
set-wallpaper &
xcompmgr &
dwmblocks &
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &
com.github.wwmm.easyeffects --gapplication-service &
while true :; do
  dwm
done
